# index:
#     path: /
#     controller: App\Controller\GenreController::accueil

liste_genre:
     path: /liste
     controller: App\Controller\GenreController::listeGenre
liste_genres_acteur:
     path: /liste-deux-films
     controller: App\Controller\GenreController::listeGenreActeurDeuxFilms
duree_films_pour_genre:
     path : /duree-films
     controller: App\Controller\GenreController::dureeFilmsPourUnGenre
supprimer_genre_sans_film:
     path: /supprimer-genre-sans-film/
     controller: App\Controller\GenreController::supprimerGenreSansFilm
supprimer_genre:
     path: /supprimer-genre/{id}
     controller: App\Controller\GenreController::supprimerGenre
     requirements: 
        id: \d+