# index:
#     path: /
#     controller: App\Controller\FilmController::accueil

liste_film:
     path: /liste-film
     controller: App\Controller\FilmController::listeFilm
detail_film:
     path: /detail-film/{id}
     controller: App\Controller\FilmController::detailFilm
     requirements:
          id: \d+
modifier_film:
     path: /modifier-film/{id}
     controller: App\Controller\FilmController::modifierFilm
     requirements:
          id: \d+
modifier2_film: 
     path: /modifier2-film/{id}
     controller: App\Controller\FilmController::modifierFilm
     requirements:
          id: \d+ 
ajouter_film:
     path: /ajouter-film
     controller: App\Controller\FilmController::ajouterFilm
supprimer_film:
     path: /supprimer-film/{id}
     controller: App\Controller\FilmController::supprimerFilm
     requirements:
          id: \d+ 
# * * * Action 13 * * * 
film_entre_deux_annees:
     path: /film-entre-deux-ans/
     controller: App\Controller\FilmController::entreDeuxAnnees
# * * * Action 14 * * * 
film_avant_une_annee:
     path: /liste-avant-une-annee/
     controller: App\Controller\FilmController::avantUneAnnee
     
liste_film_acteur:
     path: /liste-film/{id}
     controller: App\Controller\FilmController::listeFilmActeur
     requirements: 
        id: \d+
liste_acteur_3film:
     path: /liste-acteur-3film/
     controller: App\Controller\FilmController::listeActeur3Film
liste_film_acteur_chronologique:
     path: /liste-film-chronologique/
     controller: App\Controller\FilmController::listeFilmChronologique
augmenter_note_film:
     path: /augmenter-note-film/{note}
     controller: App\Controller\FilmController::augmenterNoteFilm
     requirements: 
        note: \d+
recherche_film_partie_titre:
     path: /rechercher-film-partie-titre/{partie}
     controller: App\Controller\FilmController::rechercheFilmPartieTitre
