# index:
#     path: /
#     controller: App\Controller\FilmController::accueil

# * * * Action 8 et 10* * * 
liste_film:
     path: /liste
     controller: App\Controller\FilmController::listeFilm
# * * * Action 9 * * * 
detail_film:
     path: /detail/{id}
     controller: App\Controller\FilmController::detailFilm
     requirements:
          id: \d+
# * * * Action 11 * * * 
modifier_film:
     path: /modifier/{id}
     controller: App\Controller\FilmController::modifierFilm
     requirements:
          id: \d+
modifier2_film: 
     path: /modifier2/{id}
     controller: App\Controller\FilmController::modifier2Film
     requirements:
          id: \d+ 
ajouter_acteur:
     path: /ajouter-acteur/{id}
     controller: App\Controller\FilmController::ajouterActeur
     requirements:
          id: \d+ 
retirer_acteur:
     path: /retirer-acteur/{id}
     controller: App\Controller\FilmController::retirerActeur
     requirements:
# * * * Action 12 * * *           
supprimer_film:
     path: /supprimer-film/{id}
     controller: App\Controller\FilmController::supprimerFilm
     requirements:
          id: \d+ 
# * * * Action 13 * * * 
film_entre_deux_annees:
     path: /film-entre-deux-ans/
     controller: App\Controller\FilmController::entreDeuxAnnees
# * * * Action 14 * * * 
film_avant_une_annee:
     path: /liste-avant-une-annee/
     controller: App\Controller\FilmController::avantUneAnnee
# * * * Action 17 * * * 
liste_film_commun:
     path: /liste-commun/
     controller: App\Controller\FilmController::listeFilmPourDeuxActeurs
# * * * Action 25 * * * 
rechercher_avec_partie_titre:
     path: /recherche
     controller: App\Controller\FilmController::rechercherAvecPartieTitre
# * * * Action 26 * * * 
augmenter_age_mini:
     path: /augmenter-age
     controller: App\Controller\FilmController::augmenterAgeMiniSelonActeur