# index:
#     path: /
#     controller: App\Controller\ActeurController::accueil
# * * * Action 3 et 5* * 
liste_acteur:
     path: /liste
     controller: App\Controller\ActeurController::listeActeur
# * * * Action 4 * * 
detail_acteur:
     path: /detail/{id}
     controller: App\Controller\ActeurController::detailActeur
     requirements:
          id: \d+
# * * * Action 6 * * 
modifier_acteur:
     path: /modifier/{id}
     controller: App\Controller\ActeurController::modifierActeur
     requirements:
          id: \d+
modifier2_acteur: 
     path: /modifier2/{id}
     controller: App\Controller\ActeurController::modifier2Acteur
     requirements:
          id: \d+         
# * * * Action 12 * * 
supprimer_acteur:
     path: /supprimer/{id}
     controller: App\Controller\ActeurController::supprimerActeur
     requirements:
          id: \d+ 
# * * * Action 15 * * 
liste_acteurs_selon_film:
     path: /acteurs-selon-film/
     controller: App\Controller\ActeurController::acteurSelonFilm
# * * * Action 16 * * 
liste_acteurs_trois_films:
     path: /acteurs-trois-films/
     controller: App\Controller\ActeurController::acteurAvecTroisFilms
# * * * Action 20 * * 
liste_acteurs_film_chrono:
     path: /acteurs-films-chrono/
     controller: App\Controller\ActeurController::listeActeursFilmChrono
