# index:
#     path: /
#     controller: App\Controller\CinelandController::accueil
menu:
     path: /menu
     controller: App\Controller\CinelandController::menu
acteur: 
    resource: routes/acteur/routes.yaml
    prefix: /acteur
film: 
    resource: routes/film/routes.yaml
    prefix: /film
genre: 
    resource: routes/genre/routes.yaml
    prefix: /genre
pageNotFound:
    path:  /{pathing}
    controller: App\Controller\CinelandController::pageNotFound
    requirements:
        pathing: .*